<a href="https://colab.research.google.com/github/EddyGiusepe/Repasso_Python/blob/main/Remembering_NumPy_Eddy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <h2 align="center">Remembering the use of Numpy</h2>

Data Scientist.: Dr.Eddy Giusepe Chirinos Isidro



Link de estudo:

* [Arrays (arreglos) de NumPy para processar Dados](https://www.youtube.com/watch?v=LVq_8mworXM&list=PLat2DtY8K7YUG6xFMkS185GCPIxcKRXyN&index=1)


* [Código Máquina](https://github.com/CodigoMaquina/code)

In [ ]:
# Importamos a nossa biblioteca

import numpy as np

In [ ]:
# criamos um "arreglo" (uma lista) e a convertemos a NumPy

arreglo = np.array([1, 2, 3, 4, 5, 6])

# ou podemos criar esse arreglo assim, também:

arreglo = np.arange(1, 7)

arreglo

array([1, 2, 3, 4, 5, 6])

In [ ]:
type(arreglo)

numpy.ndarray

In [ ]:
arreglo[0]

1

In [ ]:
# sub-lista
arreglo[1:4]

array([2, 3, 4])

In [ ]:
#Modificando um elemento do arreglo

arreglo[0] = 45 

In [ ]:
# Ai veremos o Dado modificado 

arreglo

array([45,  2,  3,  4,  5,  6])

In [ ]:
# tamanho do arreglo

arreglo.size

6

In [ ]:
# Assim, também:

len(arreglo)


6

In [ ]:
# Ordem crescente

arreglo.sort()
arreglo

array([ 2,  3,  4,  5,  6, 45])

In [ ]:
# Ordem invertido para este momento. Se quiser modificar de vez, você teria que criar um novo arreglo

arreglo[::-1]

array([45,  6,  5,  4,  3,  2])

In [ ]:
# Tipo de Dados que tem meu array (arreglo)

arreglo.dtype

dtype('int64')

In [ ]:
# Vamos a criar novamente nosso arreglo, só que vamos a indicar o tipo de Dado

arreglo = np.array([1, 2, 3, 4, 5, 6], dtype = 'i') # i --> significa INTEIRO
arreglo

array([1, 2, 3, 4, 5, 6], dtype=int32)

In [ ]:
print(arreglo, arreglo.dtype, arreglo.itemsize) # itemsize --> Quantidade de byte que ocupa os elementos

[1 2 3 4 5 6] int32 4


In [ ]:
# 4byte por inteiro

arreglo = np.array([1, 2, 3, 4, 5, 6], dtype = 'i')
print(arreglo, arreglo.dtype, arreglo.itemsize) 

[1 2 3 4 5 6] int32 4


In [ ]:
# 2byte por inteiro

arreglo = np.array([1, 2, 3, 4, 5, 6], dtype = 'i2')
print(arreglo, arreglo.dtype, arreglo.itemsize) 

[1 2 3 4 5 6] int16 2


In [ ]:
# 4byte por inteiro

arreglo = np.array([1, 2, 3, 4, 5, 6], dtype = 'i4')
print(arreglo, arreglo.dtype, arreglo.itemsize) 

[1 2 3 4 5 6] int32 4


In [ ]:
# 8byte por inteiro

arreglo = np.array([1, 2, 3, 4, 5, 6], dtype = 'i8')
print(arreglo, arreglo.dtype, arreglo.itemsize) 

[1 2 3 4 5 6] int64 8


In [ ]:
# Há que ter cuidado com o SEGUINTE
# Vamos modificar apenas um valor e ver o comportamento 


# 2byte por inteiro
arreglo = np.array([1000000000, 2, 3, 4, 5, 6], dtype = 'i2')
print(arreglo, arreglo.dtype, arreglo.itemsize) 

# OBSERVAMOS que NumPy colocou apenas um valor o qual não é verdadeiro. CUIDADO!!!

[-13824      2      3      4      5      6] int16 2


In [ ]:
# 4byte por inteiro

arreglo = np.array([1000000000, 2, 3, 4, 5, 6], dtype = 'i4')
print(arreglo, arreglo.dtype, arreglo.itemsize) 

# Aqui o valor não se modificou

[1000000000          2          3          4          5          6] int32 4


In [ ]:
# Usando shape

arreglo = np.array([1, 2, 3, 4, 5, 6])

In [ ]:
arreglo.shape

# Aqui temos 6 elemento e apenas UMA DIMENSÃO

(6,)

In [ ]:
# Modificando o shape com reshape

arreglo.reshape((2, 3))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arreglo.reshape((3, 2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
arreglo

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.append(arreglo, 7) # Adiciona ao final (mas não modificamos nosso arreglo)

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
# Modificando mesmo

arreglo = np.append(arreglo, 9)

In [ ]:
arreglo

array([1, 2, 3, 4, 5, 6, 9])

In [ ]:
# insert(seu_array, posição, valor_adicionar)

arreglo = np.insert(arreglo, 1, 9)

In [ ]:
arreglo

array([1, 9, 2, 3, 4, 5, 6, 9])

In [ ]:
# Eliminado elemento 

np.delete(arreglo, 2) # 2--> é a posição deo elemento a eliminar

array([1, 9, 3, 4, 5, 6, 9])

In [ ]:
arreglo

array([1, 9, 2, 3, 4, 5, 6, 9])

In [ ]:
# O where não é um método é uma subrutina do NumPy (não confundir com Método)

np.where(arreglo == 9) # Traz as posições onde há número 9

(array([1, 7]),)

In [ ]:
# Temos:

arreglo


array([1, 9, 2, 3, 4, 5, 6, 9])

In [ ]:
arreglo + 1 # Operação vectorial


array([ 2, 10,  3,  4,  5,  6,  7, 10])

In [ ]:
# Multiplicação por 2

arreglo*2

array([ 2, 18,  4,  6,  8, 10, 12, 18])

In [ ]:
# Também:

arreglo*arreglo

array([ 1, 81,  4,  9, 16, 25, 36, 81])

In [ ]:
# Observar que os Dados em NumPy tem que ser homogêneos (a diferença dos Dados em uma Lista)
altura = np.array([1.74, 1.8, 1.78, 1.68, 1.78, 1.7, 1.74, 1.74, 1.73, 1.79, 
           1.78, 1.72, 1.65, 1.78, 1.7, 1.68, 1.79, 1.68, 1.82, 1.72,
           1.75, 1.66, 1.67, 1.79, 1.75, 1.65, 1.78, 1.73, 1.71, 1.81,
           1.73, 1.71, 1.68, 1.74, 1.75, 1.68, 1.74, 1.81, 1.73, 1.82,
           1.8, 1.67, 1.73, 1.7, 1.73, 1.7, 1.81, 1.81, 1.76, 1.82, 1.68,
           1.74, 1.65, 1.8, 1.78, 1.7, 1.68, 1.78, 1.79, 1.73, 1.64, 1.67,
           1.69, 1.74, 1.76, 1.66, 1.66, 1.73, 1.79, 1.81, 1.78, 1.63,
           1.76, 1.72, 1.71, 1.7, 1.62, 1.8, 1.75, 1.8, 1.78, 1.78, 1.76,
           1.65, 1.65, 1.68, 1.74, 1.75, 1.69, 1.75, 1.7, 1.83, 1.64, 1.7,
           1.69, 1.69, 1.64, 1.69, 1.77, 1.8, 1.78, 1.69, 1.7, 1.7, 1.7,
           1.63, 1.73, 1.84, 1.66, 1.78, 1.8, 1.79, 1.78, 1.74, 1.77,
           1.73, 1.77, 1.76, 1.75, 1.8, 1.75,  1.8, 1.79, 1.71, 1.73,
           1.59, 1.76, 1.75, 1.71, 1.76, 1.8, 1.68, 1.74, 1.77, 1.73,
           1.68, 1.63, 1.67])

peso = np.array([81.4, 88.7, 87.3, 62.7, 81.6, 80.9, 74.6, 84.7, 76.7, 88.3,
         84.6, 74, 57.7, 84.1, 79.7, 63.8, 88.4, 71.2, 87.1, 67, 80.7,
         74.7, 60.5, 85.9, 72.4, 59.7, 87.3, 85.7, 64.1, 91.9, 82.8, 75.7,
         60.2, 73.1, 74.7, 65.9, 80.9, 91.3, 76, 86.8, 80.7, 74.2, 83.1,
         77.8, 84.5, 58.8, 89.5, 87, 84, 89.9, 56.5, 80.2, 61.8, 86.3,
         82.6, 69.4, 65.8, 79.3, 88.1, 78.5, 69.1, 62.5, 74, 74.4, 87.6,
         59.6, 61.4, 83.2, 89.2, 89.2, 103.7, 67.9, 85.4, 69.5, 75.7, 
         83.9, 59.5, 87.9, 82.6, 88.1, 86.2, 88.9, 84.4, 58.4, 61.5, 69.2,
         84.2, 78, 81.1, 81.5, 74.7, 90.4, 59.2, 79.3, 65.1, 93, 60.5,
         76.4, 98.8, 89.1, 88.9, 61.1, 76.6, 86, 75.5, 66.9, 79.4, 87.9,
         72.3, 93.8, 89, 90.7, 86.7, 77.6, 85.1, 91.8, 103.2, 91.1, 67,
         86.9, 78.7, 87.1, 85.5, 69.8, 75, 53.9, 99, 93.7, 88, 79.4, 87.6,
         60.4, 82.7, 90.6, 79.8, 61.2, 62.5, 59.7])   

In [ ]:
# Índice de massa corporal

imc = peso/(altura)**2

# IMPORTANTA: Esta expressão vai realizar uma operação VECTORIAL


In [ ]:
imc

array([26.8859823 , 27.37654321, 27.55333922, 22.21513605, 25.75432395,
       27.99307958, 24.63997886, 27.97595455, 25.62731799, 27.55844075,
       26.70117409, 25.01352082, 21.19375574, 26.54336574, 27.57785467,
       22.60487528, 27.58965076, 25.22675737, 26.29513344, 22.64737696,
       26.35102041, 27.10843373, 21.69314066, 26.80940046, 23.64081633,
       21.92837466, 27.55333922, 28.63443483, 21.92127492, 28.05164678,
       27.66547496, 25.88830751, 21.32936508, 24.14453693, 24.39183673,
       23.3489229 , 26.72083498, 27.86850218, 25.39343112, 26.20456467,
       24.90740741, 26.60547169, 27.76571219, 26.92041522, 28.23348592,
       20.34602076, 27.3190684 , 26.55596594, 27.1177686 , 27.14044198,
       20.01842404, 26.48962875, 22.69972452, 26.63580247, 26.06994066,
       24.01384083, 23.31349206, 25.0284055 , 27.49602072, 26.22874135,
       25.69155265, 22.41026928, 25.90945695, 24.57391994, 28.27995868,
       21.62868341, 22.28189868, 27.79912459, 27.83933086, 27.22

In [ ]:
# Calculamos a média

imc.mean()

26.003202440484596

In [ ]:
# Como huviesse sido feito como LISTA? 

imc = []

for i in range(altura.size):
  imc.append(peso[i] / (altura[i]*altura[i]))


# Isto é uma forma iterativa
# Mas com NumPy é melhor, já que feita através do uso de operações vectoriais 

In [ ]:
# Observamos que o resultado é uma lista

imc

[26.88598229620822,
 27.37654320987654,
 27.553339224845345,
 22.215136054421773,
 25.754323948996337,
 27.993079584775092,
 24.639978861144137,
 27.975954551459903,
 25.627317985899964,
 27.55844074779189,
 26.701174094180026,
 25.013520822065985,
 21.19375573921029,
 26.54336573664941,
 27.57785467128028,
 22.604875283446713,
 27.5896507599638,
 25.226757369614518,
 26.29513343799058,
 22.647376960519203,
 26.351020408163265,
 27.108433734939762,
 21.693140664778227,
 26.80940045566618,
 23.640816326530615,
 21.928374655647385,
 27.553339224845345,
 28.634434829095525,
 21.921274922198283,
 28.051646775128965,
 27.665474957399177,
 25.888307513422937,
 21.329365079365083,
 24.144536926938827,
 24.39183673469388,
 23.348922902494337,
 26.720834984806448,
 27.868502182473062,
 25.393431120318084,
 26.204564666103124,
 24.90740740740741,
 26.605471691347844,
 27.765712185505695,
 26.920415224913498,
 28.23348591666945,
 20.346020761245676,
 27.319068404505355,
 26.555965935105768,
 27.1